baseURL: 'https://repinger.com/'
languageCode: en-us
title: repinger
theme: terminal
minify:
  minifyOutput: true
params:
  centerTheme: true
  favicon: favicon.png
  hidePowered: true
languages:
  en:
    copyright: Â© 2025 | @repinger
    params:
      logo:
        logoText: repinger
