baseURL: 'https://dns.repinger.my.id/'
languageCode: en-us
title: Privacy DNS
theme: hugo-bearcub
copyright: Â© 2023
defaultContentLanguage: en
enableRobotsTXT: true
minify:
  minifyOutput: true
languages:
  en:
    languageName: "en-US ðŸ‡ºðŸ‡¸"
    LanguageCode: en-US
    contentDir: content
    params:
      madeWith: '[@repinger](https://repinger.my.id)'
params:
  favicon: favicon.png
  hideHeader: true
